export const StyleSetClockScreen = {
  textItemDay: {
    padding: 10,
    textAlign: 'center',
    fontSize: 14,
    color: 'white',
  },
  nameTextInput: {
    padding: 10,
    backgroundColor: 'white',
    height: 50,
    width: '100%',
    borderColor: 'rgba(0,0,0,0.1)',
    borderWidth: 0.2,
    marginTop: 10,
    borderBottomColor: 'rgba(0,0,0,0.5)',
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
  },
  containerButton: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  containerFlatList: {backgroundColor: 'white'},
  containerDatePicker: {
    width: '100%',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  ContainerButtonAddAction: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  containerTouch: {
    width: '90%',
    alignItems: 'center',
    height: 50,
    justifyContent: 'center',
    borderRadius: 5,
  },
  textAddAction: {fontSize: 20, color: 'white'},
  containerItem: {
    width: 100,
    height: 30,
    justifyContent: 'center',
    borderRadius: 20,
    marginLeft: 10,
    marginBottom: 10,
    marginTop: 3,
    borderWidth: 1,
  },
  touchButtonLoop: {
    width: '50%',
    height: 50,
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  textButtonLoop: {padding: 10, textAlign: 'center', fontSize: 14},
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: 'gray',
    backgroundColor: 'white',
    paddingVertical: 10,
  },
  textHeader:{fontSize: 18, marginTop: 3,marginRight:5},
  textSave:{color:'#1291b6',marginRight:10,fontSize:20}
};
