export const styleMenuDetail = {
    ContainerTTCB: {
        flex: 2 / 4,
        justifyContent: 'center',
        borderBottomWidth: 0.5,
    },
    textTTCB: {marginLeft: 15, fontSize: 20},
    containerTTB: {
        flex: 2 / 4,
        width: '100%',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottomWidth: 0.5,
        borderColor: 'gray',
        backgroundColor: 'white',
    },
    containerSubTTB: {flexDirection: 'row', marginLeft: 15, alignItems: 'center'},
    TTB: {fontSize: 20},
    subTTB: {marginLeft: 20, marginTop: 5},
    iconEdit: {fontSize: 30, color: '#1291b6', marginRight: 8},
    containerTTA: {
        flex: 2 / 4,
        justifyContent: 'center',
        borderBottomWidth: 0.5,
        borderColor: 'gray',
        backgroundColor: 'white',
    },
    TTA: {marginLeft: 10, fontSize: 20},
    VTTB: {marginLeft: 17, fontSize: 15},
    CXL: {marginRight: 10},
    containerVoice: {
        height: 50,
        justifyContent: 'space-around',
        borderBottomWidth: 0.5,
    },
    containerTTCDK: {
        height: 50,

        justifyContent: 'center',
        borderBottomWidth: 0.5,
        borderColor: 'gray',
    },
    containerTB: {
        height: 50,

        justifyContent: 'center',
        borderBottomWidth: 0.5,
        borderColor: 'gray',
    },
    containerShare: {
        height: 50,
        justifyContent: 'center',
        borderBottomWidth: 0.5,
        borderColor: 'gray',
        backgroundColor: 'white',
    },
    containerCheckPM: {
        height: 50,
        justifyContent: 'center',
        borderBottomWidth: 0.5,
        borderColor: 'gray',
    },
    textCheckPM: {marginLeft: 15, fontSize: 20, color: 'gray'},
    buttonDelete: {
        width: '90%',
        borderRadius: 70,
        height: 35,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 5,
        backgroundColor: 'red',
    },
};
