export const styleItemAddDevice = {
  marginVertical: 10,
  marginHorizontal: 15,
  width: 150,
  borderRadius: 10,
  overflow: 'hidden',
  padding: 3,
  backgroundColor: 'white',
  shadowColor: '#000',
  shadowOffset: {
    width: 0,
    height: 1,
  },
  shadowOpacity: 0.2,
  shadowRadius: 1.41,
  elevation: 2,
  alignItems: 'center',
  justifyContent: 'center',
  height: 90,
};
