export const styleItem = {
  container: {
    marginVertical: 10,
    marginHorizontal: 15,
    width: 150,
    borderRadius: 10,
    overflow: 'hidden',
    padding: 3,
    backgroundColor: 'white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  title: {
    marginBottom: 5,
    backgroundColor: '#DCDCDC',
    borderTopLeftRadius: 5,
    borderTopRightRadius: 5,
  },
  body: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  Icon: {
    width: 40,
    height: 40,
    borderRadius: 40 / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.5,
    borderColor: 'gray',
  },
  Image: {width: 70, height: 60},
};
