export const stylesLogin = {
  container: {
    marginHorizontal: 30,
    flex: 1,
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  imageBackGround: {
    resizeMode: 'contain',
    height: 500,
    width: 500,
    position: 'absolute',
  },
  nation: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'gray',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: 50,
    backgroundColor: 'white',
  },
  phonenumber: {
    borderColor: 'gray',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    width: '100%',
    height: 50,
    backgroundColor: 'white',
  },
  blockPass: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'gray',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    height: 50,
    backgroundColor: 'white',
  },
  iconEye: {
    width: 40,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  styleIcon: {
    paddingRight: 5,
    color: 'black',
  },
  smallNation: {
    flex: 1,
    paddingLeft: 5,
  },
  callCode: {
    textAlign: 'center',
    paddingRight: 5,
  },
};
export const stylesForgetPass = {
  container: {
    marginHorizontal: 30,
    flex: 1,
    alignItems: 'center',
    borderRadius: 5,
    marginTop: 10,
  },
  imageBackGround: {
    resizeMode: 'contain',
    height: 500,
    width: 500,
    position: 'absolute',
  },
  nation: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'gray',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: 50,
    backgroundColor: 'white',
  },
  phonenumber: {
    backgroundColor: 'white',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'gray',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  blockPass: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'gray',
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    height: 50,
    backgroundColor: 'white',
  },
  iconEye: {
    width: 40,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  styleIcon: {
    paddingRight: 5,
    color: 'black',
  },
  buttonLogin: {
    width: '100%',
    borderRadius: 70,
    height: 35,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
    backgroundColor: '#1291b6',
  },
  smallNation: {
    flex: 1,
    paddingLeft: 5,
  },
  callCode: {
    textAlign: 'center',
    paddingRight: 5,
  },
};
export const stylesInputMXN = {
  container: {
    marginHorizontal: 30,
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: 'pink',
  },
  imageBackGround: {
    resizeMode: 'contain',
    height: 500,
    width: 500,
    position: 'absolute',
  },
  phonenumber: {
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 10,
    width: '100%',
    height: 50,
    backgroundColor: 'white',
  },
  noti: {
    justifyContent: 'center',
    alignItems: 'center',
  },
};
export const stylesNewPass = {
  container: {
    marginHorizontal: 30,
    alignItems: 'center',
    marginTop: 10,
  },
  imageBackGround: {
    resizeMode: 'contain',
    height: 500,
    width: 500,
    position: 'absolute',
  },
  phonenumber: {
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 10,
    width: '100%',
    height: 50,
    backgroundColor: 'white',
  },
  blockPass: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 10,
    height: 50,
    backgroundColor: 'white',
  },
  iconEye: {
    width: 40,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
};
export const stylesUserInfor = {
  containerFirst: {
    backgroundColor: 'white',
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  containerFirstItem: {justifyContent: 'center', alignItems: 'center'},
  circleIcon: {
    width: 150,
    height: 150,
    borderRadius: 150 / 2,
    backgroundColor: '#d8d8d8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {backgroundColor: '#f7f7f7', flex: 1, marginTop: 10},
  changePass: {
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderColor: 'gray',
  },
  text: {marginTop: 15},
  iconAngle: {
    width: 15,
    marginTop: 15,
    fontSize: 20,
  },
  containerPhanhoi: {
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f9f9f9',
  },
  containerPBUD: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    height: 50,
    backgroundColor: 'white',
  },
  version: {width: 80, marginTop: 15},
};
export const stylesSplash = {
  BlockStyle: {
    backgroundColor: '#DCDCDC',
    borderRadius: 2,
    height: 50,
    width: 150,
    alignItems: 'center',
  },
  Logo: {
    textAlign: 'center',
    color: '#1E90FF',
    paddingTop: 15,
  },
  viewStyles: {
    flex: 2,
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: 'white',
    flexDirection: 'column',
    paddingTop: 200,
  },
  textStyles: {
    color: 'black',
    fontSize: 10,
    fontWeight: 'bold',
  },
};
